# Generated by Django 2.1.7 on 2019-04-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190427_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='max_elo',
            field=models.DecimalField(decimal_places=2, default=800, max_digits=6),
        ),
        migrations.AlterField(
            model_name='game',
            name='change',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='game',
            name='elo1',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='game',
            name='elo2',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player',
            name='elo',
            field=models.DecimalField(decimal_places=2, default=800, max_digits=6),
        ),
    ]
