# Generated by Django 2.1.7 on 2019-04-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190427_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='max_elo',
        ),
    ]
