# Generated by Django 2.1.7 on 2019-05-21 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190509_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='streak',
        ),
    ]
